### ISSUE TITLE
Can't render blocks conditionally

### ISSUE THREAD

**Issue by amk221** [ember-polyfills/ember-named-blocks-polyfill#25]
Is there a technical reason we can't do this:

```handlebars
<MyComponent>
  {{#if this.showGreeting}}
    <:greeting>
      Hello World
    </:greeting>
  {{/if}}
</MyComponent>
```
```
Syntax Error: Unexpected named block <:greeting> (on line 3 column 4)
```

[Demo repo](https://github.com/amk221/-ember-conditional-named-blocks/commit/ca6888acbdd087c401d83b2295969de18e07c42d)

**Comment by rwjblue** [comment]
Ya, the mental model here is just a bit wrong. You aren't "rendering named blocks" you are **passing** them into the component invocation.

**Comment by rwjblue** [comment]
Also, I think this is a duplicate of https://github.com/ember-polyfills/ember-named-blocks-polyfill/issues/21.

**Comment by amk221** [comment]
Thanks for explaining.

I think given the `if` here:

```handlebars
{{! my-component.hbs }}
{{#if (has-block "greeting")}}
  <div class="my-component__greeting">
    {{yield to="greeting"}}
  </div>
{{/if}}
```

...made me think it was possbile.

But yep, I understand, thanks
