### ISSUE TITLE
Broken in Ember 3.21?

### ISSUE THREAD

**Issue by jherdman** [ember-polyfills/ember-named-blocks-polyfill#27]
Precision Nutrition has an internal addon (i.e. published, but private) that utilizes this addon, and correctly lists it as a "dependnecy". We're seeing the following warning when trying to upgrade to Ember 3.12:

```
Assertion Failed: Named blocks are not currently available, attempted to yield to a named block other than "default" or "inverse": {{yield to="image"}}. ('@precision-nutrition/our-private-addon/components/some-component/item.hbs' @ L17:C6)
```

The host application ALSO lists this addon as a devDependency.

**Comment by jherdman** [comment]
I can also confirm this is broken within our addon itself. I think this means the repro will be easy to replicate.

**Comment by chancancode** [comment]
which version of the polyfill do you have?

**Comment by jherdman** [comment]
0.2.1. I'm in the process of confirming the latest patch resolves my issue. Thank you for your speedy reply.

**Comment by jherdman** [comment]
Confirmed 0.2.3 fixes my problem.
