### ISSUE TITLE
Upstream strict syntax checks

### ISSUE THREAD

**Issue by chancancode** [ember-polyfills/ember-named-blocks-polyfill#3]
* [x] Block names must start with lowercase letters:

  ```hbs
  <FancyList>
    <:Foo>...</:Foo>
    ~~~~~~
    Syntax Error: <:Foo> is not a valid named block: `Foo` is not a valid
    block name
  </FancyList>
  ```

* [x] Named blocks cannot be self-closing:

  ```hbs
  <FancyList>
    <:foo />
    ~~~~~~~~
    Syntax Error: <:Foo> is not a valid named block: named blocks cannot be
    self-closing
  </FancyList>
  ```

* [x] Passing named blocks to HTML elements:

  ```hbs
  <div>
    <:foo>...</:foo>
    ~~~~~~
      Syntax Error: Unexpected named block <:foo> inside <div> HTML element
  </div>
  ```

* [x] Mixing named blocks and other non-whitespace, non-comment content:

  ```hbs
  <FancyList>
    {{!-- comments are allowed --}}

    <:header>My Header</:header>

    <div>Some content</div>
    ~~~~~
    Syntax Error: Unexpected content inside <FancyList> component invocation:
    when using named blocks, the tag cannot contain other content
  </FancyList>
  ```

* [x] Block params on component invocations with named blocks:

  ```hbs
  <FancyList as |item|>
  ~~~~~~~~~~~~~~~~~~~~~
  Syntax Error: Unexpected block params list on <FancyList> component
  invocation: when passing named blocks, the invocation tag cannot take block
  params
    <:row>The {{item}}</:row>
  </FancyList>
  ```

* [x] Passing arguments, attribues or modifiers to named blocks:

  ```hbs
  <FancyList>
    <:header class="row">My Header</:header>
              ~~~~~~~~~~~
              Syntax Error: named block <:header> cannot have attribues or
              arguments
  </FancyList>
  ```

* [x] Passing the same named blocks more than once:

  ```hbs
  <FancyList>
    <:header>My Header</:header>
    <:header>It's me again!</:header>
    ~~~~~~~~~
    Syntax Error: Cannot pass named block <:header> twice in the same
    invocation
  </FancyList>
  ```

  ```hbs
  <FancyList>
    <:else>The else block</:else>
    <:inverse>The inverse block</:inverse>
    ~~~~~~~~~~
    Syntax Error: Cannot pass named blocks <:else> and <:inverse> in the same
    invocation
  </FancyList>
  ```

* [x] Passing invalid arguments to `{{yield}}`, `{{has-block}}` and
  `{{has-block-params}}` or passing anything other than a string literal for
  the block name argument:

  ```hbs
  {{yield block="foo"}}
                ~~~~~
                Syntax Error: Cannot pass block named argument to {{yield}}
  ```

  ```hbs
  {{has-block this.block}}
              ~~~~~~~~~~
              Syntax Error: {{has-block}} can only accept a string literal
              argument
  ```

* [ ] Other miscellaneous checks not directly related to named blocks (search the plugin code for `assert(...)` and `check(...)`)

**Comment by locks** [comment]
`main` and `default` are not aliases, so the error above doesn't not seem correct. `main` only existed as an internal name for the default block.

For `inverse` and `else`, this means upstreaming a change making them aliases, c? At the moment you cannot  use `<:inverse>` because internally rename `inverse` to `else`.

I am not sure what "Passing invalid arguments to {{yield}}…" is demonstrating. Is the block named argument saying that you cannot pass named arguments to `yield` other than `to`?

**Comment by buschtoens** [comment]
Can you explain why block params are prohibited?

> Block params on component invocations with named blocks:
> 
> ```hbs
> <FancyList as |item|>
> ~~~~~~~~~~~~~~~~~~~~~
> Syntax Error: Unexpected block params list on <FancyList> component
> invocation: when passing named blocks, the invocation tag cannot take block
> params
>   <:row>The {{item}}</:row>
> </FancyList>
> ```

I think this is actually a very valid use-case and it's not apparent to me, why it should be forbidden.
Thanks. 🙏

**Comment by buschtoens** [comment]
Ah. Sorry. I looked at the RFC now and yes of course this restriction makes sense. You would yield block params on the blocks, not the root invocation.

```hbs
<FancyList>
  <:row as |item|>The {{item}}</:row>
</FancyList>
```

This works.

**Comment by locks** [comment]
Ah, was writing up a response xD Yes, exactly. You cannot use the implicit default block and named blocks at the same time, so you couldn't yield out the values.

**Comment by chancancode** [comment]
This is done
